name: build

on:
  push:
    branches:
      - 'main'

jobs:
  php8-0:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cloudynes
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: List files
        run: ls -la

      - name: Build and push PHP7.4 Unit Image (debian)
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/cloudynes/unit-php:cache
          cache-to: type=registry,ref=ghcr.io/cloudynes/unit-php:cache
          context: ./unit/php
          file: ./unit/php/7.4
          push: true
          tags: |
            cloudyne/unit-php:7.4
            cloudyne/unit-php:7
            ghcr.io/cloudynes/unit-php:7.4
            ghcr.io/cloudynes/unit-php:7
      
      - name: Build and push PHP7.4 Bedrock Image (debian)
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/cloudynes/bedrock-php:cache
          cache-to: type=registry,ref=ghcr.io/cloudynes/bedrock-php:cache
          context: ./bedrock
          file: ./bedrock/7.4
          push: true
          tags: |
            cloudyne/bedrock-php:7.4
            cloudyne/bedrock-php:7
            ghcr.io/cloudynes/bedrock-php:7.4
            ghcr.io/cloudynes/bedrock-php:7

      - name: Build and push nginx image (nginx:1.21.3-alpine)
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/cloudynes/php-nginx:cache
          cache-to: type=registry,ref=ghcr.io/cloudynes/php-nginx:cache
          context: ./php-nginx
          file: ./php-nginx/Dockerfile
          push: true
          build-args: |
            PHP_VERSION=7.4
            ALPINE_VERSION=3.16
          tags: |
            ghcr.io/cloudynes/php-nginx:fpm7.4-alpine3.16
            ghcr.io/cloudynes/php-nginx:fpm7.4-alpine

      - name: Build and push init image
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/cloudynes/php-init:cache
          cache-to: type=registry,ref=ghcr.io/cloudynes/php-init:cache
          context: ./php-init
          file: ./php-init/Dockerfile
          push: true
          build-args: |
            PHP_VERSION=7.4
            ALPINE_VERSION=3.16
          tags: |
            ghcr.io/cloudynes/php-init:fpm7.4-alpine3.16
            ghcr.io/cloudynes/php-init:fpm7.4-alpine