name: build
on:
  push:
    branches:
      - main
      - unit
      - precompiled-images

jobs:
  php-builds:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '7.4', '8.0', '8.1', '8.2' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cloudynes
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.AZURECR_URL }}
          username: ${{ secrets.AZURECR_USER }}
          password: ${{ secrets.AZURECR_SECRET }}
      
      - name: Build and push php-extended
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/cloudynes/php-extended:cache
          cache-to: type=registry,ref=ghcr.io/cloudynes/php-extended:cache
          context: ./php-extended
          file: ./php-extended/Dockerfile
          push: true
          build-args: |
              SOURCE_VERSION=${{ matrix.php }}
          tags: |
              ghcr.io/cloudynes/php-extended:${{ matrix.php }}
              cloudyne/php-extended:${{ matrix.php }}

      - name: Build and push php-unit
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/cloudynes/php-unit:cache
          cache-to: type=registry,ref=ghcr.io/cloudynes/php-unit:cache
          context: ./php-unit
          file: ./php-unit/Dockerfile
          push: true
          build-args: |
              SOURCE_VERSION=${{ matrix.php }}
          tags: |
              ghcr.io/cloudynes/php-unit:${{ matrix.php }}
              cloudyne/php-unit:${{ matrix.php }}

      - name: Build and push php-bedrock
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=cloudyne.azurecr.io/php-bedrock:cache
          cache-to: type=registry,ref=cloudyne.azurecr.io/php-bedrock:cache
          context: ./php-bedrock
          file: ./php-bedrock/Dockerfile
          push: true
          build-args: |
            SOURCE_VERSION=${{ matrix.php }}
          tags:
            cloudyne.azurecr.io/php-bedrock:${{ matrix.php }}
      
      - name: Build and push php-cd
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=cloudyne.azurecr.io/php-cd:cache
          cache-to: type=registry,ref=cloudyne.azurecr.io/php-cd:cache
          context: ./php-cd
          file: ./php-cd/Dockerfile
          push: true
          build-args: |
            SOURCE_VERSION=${{ matrix.php }}
          tags:
            cloudyne.azurecr.io/php-cd:${{ matrix.php }}

  php-tag-latest:
    runs-on: ubuntu-latest
    needs: php-builds
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: cloudynes
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Download, re-tag and push images
        run: |
          docker pull ghcr.io/cloudynes/php-extended:8.2
          docker tag ghcr.io/cloudynes/php-extended:8.2 ghcr.io/cloudynes/php-extended:latest
          docker push ghcr.io/cloudynes/php-extended:latest

          docker pull ghcr.io/cloudynes/php-unit:8.2
          docker tag ghcr.io/cloudynes/php-unit:8.2 ghcr.io/cloudynes/php-unit:latest
          docker push ghcr.io/cloudynes/php-unit:latest

          docker pull cloudyne.azurecr.io/php-bedrock:8.2
          docker tag cloudyne.azurecr.io/php-bedrock:8.2 cloudyne.azurecr.io/php-bedrock:latest
          docker push cloudyne.azurecr.io/php-bedrock:latest

          docker pull cloudyne.azurecr.io/php-cd:8.2
          docker tag cloudyne.azurecr.io/php-cd:8.2 cloudyne.azurecr.io/php-cd:latest
          docker push cloudyne.azurecr.io/php-cd:latest


